/**
 * @file
 * JavaScript integration between Billboard and Drupal.
 */
(function (Drupal, once) {

  'use strict';

  Drupal.behaviors.chartsBillboard = {
    attach: function (context, settings) {
      const contents = new Drupal.Charts.Contents();
      once('charts-billboard', '.charts-billboard', context).forEach(function (element) {
        const config = contents.getData(element.id);
        const title = config.title.text;
        // If the title contains '\\n', convert it to a line break.
        if (title.indexOf('\\n') !== -1) {
          config.title.text = title.replace(/\\n/g, '\n');
        }
        bb.generate(config);
        if (element.nextElementSibling && element.nextElementSibling.hasAttribute('data-charts-debug-container')) {
          element.nextElementSibling.querySelector('code').innerText = JSON.stringify(config, null, ' ');
        }
      });
    }
  };
}(Drupal, once));
;
/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(Drupal => {
  Drupal.Charts = Drupal.Charts || {};
  Drupal.Charts.Configs = Drupal.Charts.Configs || [];
  Drupal.Charts.Contents = class {
    constructor() {
      const charts_elements = document.querySelectorAll('[data-chart]');
      charts_elements.forEach(function (el) {
        const id = el.getAttribute('id');
        Drupal.Charts.Configs[id] = JSON.parse(el.getAttribute('data-chart'));
        Drupal.Charts.Configs[id].drupalChartDivElement = el;
        Drupal.Charts.Configs[id].drupalChartDivId = id;
      });
    }

    initialize(id) {
      const event = new CustomEvent('drupalChartsConfigsInitialization', {
        detail: Drupal.Charts.Configs[id]
      });
      Drupal.Charts.Configs[id].drupalChartDivElement.dispatchEvent(event);
    }

    static update(id, data) {
      if (Drupal.Charts.Configs.hasOwnProperty(id)) {
        Drupal.Charts.Configs[id] = data;
      }
    }

    getData(id) {
      if (Drupal.Charts.Configs.hasOwnProperty(id)) {
        this.initialize(id);
        return Drupal.Charts.Configs[id];
      }

      return {};
    }

  };
})(Drupal);
;
